// <auto-generated />
using System;
using HT.EFCode.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HT.EFCode.Migrations
{
    [DbContext(typeof(HTDbContext))]
    [Migration("20190328124833_HongTou_V1_1_2")]
    partial class HongTou_V1_1_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("HT.EFCode.Entitys.PermissionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CareatTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("OperationsCode")
                        .IsRequired()
                        .HasMaxLength(254);

                    b.HasKey("Id");

                    b.ToTable("HT_Permissions");
                });

            modelBuilder.Entity("HT.EFCode.Entitys.RoleAndPermissionEntity", b =>
                {
                    b.Property<long>("RoleId");

                    b.Property<long>("PermissionId");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("HT_RoleAndPermission");
                });

            modelBuilder.Entity("HT.EFCode.Entitys.RoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CareatTime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(254);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("HT_Roles");
                });

            modelBuilder.Entity("HT.EFCode.Entitys.UserAndRoleEntity", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("HT_UserAndRole");
                });

            modelBuilder.Entity("HT.EFCode.Entitys.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(254);

                    b.Property<DateTime>("CareatTime");

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<short>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue((short)1);

                    b.Property<int>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("IDCard")
                        .HasMaxLength(18);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(254);

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(24);

                    b.HasKey("Id");

                    b.HasIndex("IDCard")
                        .IsUnique();

                    b.HasIndex("PhoneNum")
                        .IsUnique();

                    b.ToTable("HT_Users");
                });

            modelBuilder.Entity("HT.EFCode.Entitys.RoleAndPermissionEntity", b =>
                {
                    b.HasOne("HT.EFCode.Entitys.PermissionEntity", "Permission")
                        .WithMany("RoleAndPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HT.EFCode.Entitys.RoleEntity", "Role")
                        .WithMany("RoleAndPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HT.EFCode.Entitys.UserAndRoleEntity", b =>
                {
                    b.HasOne("HT.EFCode.Entitys.RoleEntity", "Role")
                        .WithMany("UserAndRoleEntitys")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HT.EFCode.Entitys.UserEntity", "User")
                        .WithMany("UserAndRoleEntitys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
